### ISSUE TITLE
Laggy scrolling

### ISSUE THREAD

**Issue by filfat** [DownloadMii/DownloadMii#20]
Currently the scrolling lags quite a bit, this can by fixed by:
- Adding velocity (Which will make it possible to add swipe to scroll at a later date)
- Performance updates.

**Comment by AlbertoSONIC** [comment]
Every WaitforVBlank makes the framerate half then it was before... 

1 waitForVblank ---> 60FPS
2 waitForVBlank ---> 30FPS 

Ecc..

**Comment by filfat** [comment]
Thats somewhat true, depends. But really I'm blaming bad UI coding by me (the whole UI code needs to get re coded) and the god awful software rendering.

Sent from Windows Phone 8.1 on the Nokia Lumia 920
________________________________

**Comment by filfat** [comment]
Fixed, forgot to close this.
