### ISSUE TITLE
Downloading old app versions

### ISSUE THREAD

**Issue by celcodioc** [DownloadMii/DownloadMii#23]
Would this be a possible feature in the semi-far future of DownloadMii? The website always stores old app versions (and I don't think space is an issue there). Some users might want this, either because of potential issues in the latest version or just for taking a look at how an app was like before.

**Comment by filfat** [comment]
I haven't planned such a feature, but sure if people are interested :)

**Comment by filfat** [comment]
I'll close this for now, we can re-open it in the future if we feel like we want to add this.
