### ISSUE TITLE
Invalid license

### ISSUE THREAD

**Issue by WinterMute** [DownloadMii/DownloadMii#26]
You can't modify the GPL to add clauses which rescind user rights given by the GPL.

Section 7 invalidates your modifications so they're kind of pointless anyway.

**Comment by filfat** [comment]
Lets change license then to something more restrictive.

**Comment by WinterMute** [comment]
For what purpose?

**Comment by filfat** [comment]
Fixed,
see http://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses for more info about the Apache License

**Comment by filfat** [comment]
"For what purpose?" To not allow somebody to just take the source code of Dmii and change the name then create a quick competitor out of that.

**Comment by WinterMute** [comment]
The only way you'll prevent that is not to release your source in the first place, assuming anybody can be bothered.

You certainly won't do it by changing to a license which explicitly permits commercial use and allows derivatives to be closed source.
